version: '3.1'

services:

  db:
    image: mysql:5.7.40
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
       - "$HOME/docker/mysql/config/my.cnf:/etc/my.cnf"
       - "$HOME/docker/mysql/data:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
