version: '2'
 
services:
  ck-server:
    image: bitnami/clickhouse
    hostname: clickhouse-server
    container_name: clickhouse-server
    expose:
      - "9000"
    ports:
      - "8133:8123"
      - "9011:9000"
    volumes:
       - "$HOME/docker/clickhouse/data:/var/lib/clickhouse"
       - "$HOME/docker/clickhouse/config:/etc/clickhouse-server"
       - "$HOME/docker/clickhouse/log:/var/log/clickhouse-server"
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes 
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
        - ch_ntw

networks:
  ch_ntw:
    driver: bridge
    external: false
    ipam:
      config:
        - subnet: 10.222.1.0/24
