version: '3'

services:
  redis-server:
    image: redis
    hostname: redis-server
    container_name: redis-server
    expose:
      - "56379"
    ports:
      - "56379:56379"
    volumes:
       - "$HOME/docker/redis:/usr/local/etc/redis"
    environment:
      - TZ=Asia/Shanghai
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    command: /bin/bash -c "mkdir /data/redis && redis-server /usr/local/etc/redis/redis.conf"
